num-placeholders: 5
placeholders:
  1: http://www.google.com/
  3: ⌚
  7: https://www.google.com/
  9: firstname.secondname@domain.com
  19: www.google.com/
regexes:
- (https?:\/\/www\.\w{1,63}\.\w{1,63}(?:\/\w{0,63}){0,})
- (www\.\w{1,63}\.\w{1,63}(?:\/\w{0,63}){0,})
- ([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)
